#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build LEDE Newifi D2

on:
  push:
    branches:
      - master

env:
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Apt update
        run: sudo apt-get update

      - name: Install apt lib
        run: sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget

      - name: Clone LEDE
        run: git clone https://github.com/coolsnowwolf/lede

      - name: Update feeds
        run: cd lede && ./scripts/feeds update -a

      - name: Install feeds
        run: cd lede && ./scripts/feeds install -a

      - name: Make config
        run: |
        cd lede && make menuconfig
        mv $GITHUB_WORKSPACE/$CONFIG_FILE lede/.config

      - name: Download package
        run: |
          cd lede
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile
        run: cd lede && make -j1 V=s

