#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build LEDE Newifi D2

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-18.04
    # if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master


      - name: Load custom configuration
        run: |
          echo $GITHUB_WORKSPACE